[package]
name = "nih_plug_assets"
version = "0.1.0"
edition = "2021"
authors = ["Robbert van der Helm <mail@robbertvanderhelm.nl>"]
license = "ISC"

description = "Binary assets used in nih-plug"
repository = "https://github.com/robbert-vdh/nih_plug_assets"

[dependencies]
